### ISSUE TITLE
Installations Issues

### ISSUE THREAD

**Issue by Inmodis** [shopwareDowntown/downtown#328]
I'm just trying to support our local dealers a little bit and try to do that downtown. During the setup I came across two bugs that came up after consulting with others. The first one I could fix so far, but the second one I failed and need support.

I have a blank Debian9 Setup with Docker, docker-compose & nodejs installed.

Skipping the error does not help, as other subsequent errors will develop. Therefore I had to search for a solution for this cache error during > docker-compose build <

```
>> Cannot create cach directory /var/cache/composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
>> Cannot create directory /var/cache/composer/cache/files/, or directory is not writable. Proceeding without cache...
```
After several trial and errors...

My Solution (For all those who are desperate):
```
1. Searching for the relevant folder
find / -name composer
2. Enter the relevant subfolder at docker/overlay
cd /var/lib/docker/overlay2/<yourdockerid>/diff/var/cache
3. Setting Docker User and Docker Group as owner
chown docker:docker composer/
```
Finally Step 12 and build process passed and finished :-)

BUT, following the manual I'm stucking again at...

`bin/console system:install --create-database --basic-setup --force`

This leads into:

```
In Kernel.php line 631:
Warning: file_put_contents(/sw6/var/cache/dev_hcf0957990129b536fcc5d7064c24e0bd/srcShopware_Production_KernelDevDebugContainerDeprecations.log): failed to open stream: No such file or directory

In Kernel.php line 713:
Unable to create the cache directory (/sw6/var/cache/hcf0957990129b536fcc5d7064c24e0bd)
```

Can someone give me a hint?

**Comment by shyim** [comment]
I simplified the docker setup. Can you try again?

**Comment by Inmodis** [comment]
Thanks a lot - I really appreciate.

Following the NEW "how to install" it leads at 

> bin/console system:setup

into

`dev@3cb9edd7ab78:/var/www/html$ bin/console system:setup
PHP Warning:  require(/var/www/html/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bin/console on line 20
PHP Stack trace:
PHP   1. {main}() /var/www/html/bin/console:0
PHP Fatal error:  require(): Failed opening required '/var/www/html/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bin/console on line 20
PHP Stack trace:
PHP   1. {main}() /var/www/html/bin/console:0
dev@3cb9edd7ab78:/var/www/html$ 
`

**Comment by shyim** [comment]
Execute composer install before

**Comment by Inmodis** [comment]
Worked fine.
Next  stuck at Setup with default credentials:
`Database name [shopware]:
 > 

 ! [NOTE] Checking database credentials                                                        

                                                                                               
 [ERROR] An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory     
                                                                                               

 Retry? (yes/no) [no]:
`

**Comment by shyim** [comment]
Hostname: mysql
User: downtown
PW: uptown
Database: downtown

These are the default credentials

**Comment by Inmodis** [comment]
Awesome!

It's up and running!
