### ISSUE TITLE
Installation Issues II

### ISSUE THREAD

**Issue by Inmodis** [shopwareDowntown/downtown#331]
> After the promt Compiled successfully, the merchant portal is available at http://localhost:4200/.
Done and reachable from localhost.
But there is no Organisation/sales channel to choose which probably leads into, that it is no possible to register...

![grafik](https://user-images.githubusercontent.com/38096935/82894013-36939e00-9f52-11ea-9dd7-9f27dd017f80.png)

**Comment by shyim** [comment]
You need to change this URL
https://github.com/shopwareDowntown/downtown/blob/master/src/MerchantFrontend/src/environments/environment.ts#L9

**Comment by Inmodis** [comment]
I thought something like that after changing the port from 8000 to 80 in the simplified setup. I also checked and tried the AccessKey (Storefront and Headless) ...

Shopware.local leads to 127.0.0.1 - Right now the Headless API Key is in.

No matter what I try, I just can't get it to run ... and I've been trying since the last post :-)

**Comment by shyim** [comment]
You don't need access keys. We did removed that later one.

**Comment by Inmodis** [comment]
Well, thats my config right now:
![grafik](https://user-images.githubusercontent.com/38096935/82899299-08668c00-9f5b-11ea-9feb-0b229dbab8b3.png)

**Comment by shyim** [comment]
Can you just show the ajax requests?

**Comment by shyim** [comment]
Maybe also join us in Slack
https://slack.shopware.com
Channel #downtown its much easier :)
