### ISSUE TITLE
Failed merchant registration

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopwareDowntown/downtown#338]
Hey, I just installed downtown on a Server. Now i tried to register myself as a test merchant. I clicked on the link in the Mail and got the following Error: 

<img width="1055" alt="Bildschirmfoto 2020-10-06 um 11 12 27" src="https://user-images.githubusercontent.com/57937533/95182474-f88e6c80-07c4-11eb-8444-7af912a09667.png">

The activation code in the database was set to null, but the merchant was not activatet.

**Comment by mitelg** [comment]
`getenv` returns `false` if the given parameter name does not exist https://www.php.net/manual/en/function.getenv.php

so I guess you need to setup `MERCHANT_PORTAL` correctly in your .env file

**Comment by Nico-Schaefer-2111** [comment]
Ah, perfect. Did not recognize that it has to be put in the .env file. 
Thanks!

**Comment by Nico-Schaefer-2111** [comment]
Ah i just missed out to test the login. So the login directly after that still does not work. The database column active is still set to 0 on this merchant, but there was no error shown.

**Comment by shyim** [comment]
It will be active when the user has clicked on the mail and the portal owner has activated him
