### ISSUE TITLE
Blocked merchants get listed

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopwareDowntown/downtown#343]
Merchants which are blocked in the organisation backend in the portal are shown on the home page. This happens even when  they did not confirm their self.

**Comment by LiaraAlis** [comment]
I fixed this behavior with PR #346 
https://github.com/shopwareDowntown/downtown/pull/346/commits/7a3e7eb000ccc90cde8bdd69a9cdd39a021a7ffc
