### ISSUE TITLE
categories can only be created in english

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [shopwareDowntown/downtown#344]
Categories can only be created in english

**Comment by LiaraAlis** [comment]
In my opinion, this is not a bug.
With the cli installation of shopware, the system language is set to english. After the installation, this can not be changed. It seems that this value can only be change if the installation is done via web browser.
See also: https://docs.shopware.com/en/shopware-6-en/first-steps/installing-shopware-6#konfiguration

So you have to create the categories in english. You can change the storefront to any other language without any problems. If no translation is given, it falls back to the system language.
I don't know if it is possible to set the value via the CLI when installing shopware.
