### ISSUE TITLE
Vouchers and products are not allowed to be bought at the same time

### ISSUE THREAD

**Issue by Str0hk0pf** [shopwareDowntown/downtown#61]
The buyer-portal team already implemented a rule that products from different merchants can't be combined in the basket.

Maybe we can reuse some of their code:
https://github.com/shopware/portal/blob/master/src/Merchants/Content/Merchant/Services/CartValidator.php

**Comment by leducduc** [comment]
It's implemented on swag-voucher-funding plugin.
https://github.com/shopwareDowntown/swag-voucher-funding/blob/master/src/Service/CartValidator.php
